changelog:
  categories:
    - title: Features
      labels: [feature, enhancement]
    - title: Bug fixes
      labels: [bug, hotfix]
    - title: Documentation
      labels: [documentation]
    - title: Maintenance
      labels: [maintenance, chore, dependencies]
    - title: Other changes
      labels: ["*"]
